/*
Script Name: data_extraction.sql
Purpose: Extract and analyze data from the 'thelook_ecommerce.orders' table in BigQuery.
Author: Kittima Rodriguez
Created Date: YYYY-MM-DD
Version: 1.0
Description: 
This script retrieves and analyzes retail sales data using SQL queries. 
It counts total orders, extracts sample transactions, and identifies top-selling products.
By grouping sales by product and calculating total revenue, we determine which products perform best.
*/

-- 1️⃣ Count total orders to measure overall sales volume.
-- This tells us how many individual transactions occurred in the dataset.
SELECT COUNT(*) AS total_orders
FROM `bigquery-public-data.thelook_ecommerce.order_items`;

-- 2️⃣ Retrieve a sample of 10 sales transactions to understand the data structure and content.
-- This allows for a quick inspection of the dataset to verify data integrity and schema.
SELECT *
FROM `bigquery-public-data.thelook_ecommerce.order_items`
LIMIT 10;

-- 3️⃣ Identify the top 10 best-selling products based on total revenue.
-- This query joins the `order_items` table (which contains sales transactions) 
-- with the `products` table to retrieve product names.
-- - COUNT(o.order_id): Counts the total number of orders for each product.
-- - SUM(o.sale_price): Calculates the total revenue generated by each product.
-- Sorting by total revenue in descending order helps us find the highest-selling products.
SELECT o.product_id, p.name, COUNT(o.order_id) AS total_orders, SUM(o.sale_price) AS total_revenue
FROM `bigquery-public-data.thelook_ecommerce.order_items` AS o
JOIN `bigquery-public-data.thelook_ecommerce.products` AS p
ON o.product_id = p.id
GROUP BY o.product_id, p.name
ORDER BY total_revenue DESC
LIMIT 10;

/*
Summary:
- Total Orders: [181518]
- Sample Transactions: Retrieved 10 sample records.

/*
Top 10 Best-Selling Products:
--------------------------------------
1️⃣ JORDAN DURASHEEN SHORT MENS  
2️⃣ Catherine Malandrino Women's Skinny Stretch Leather Pant  
3️⃣ Nobis Tula Parka  
4️⃣ The North Face Nuptse 2 Jacket - Noah Green/TNF Black  
5️⃣ The North Face Freedom Mens Ski Pants 2013  
6️⃣ Canada Goose Men's The Chateau Jacket  
7️⃣ Quiksilver Men's Rockefeller Walkshort  
8️⃣ NIKE WOMEN'S PRO COMPRESSION SPORTS BRA  
9️⃣ The North Face Apex Bionic Soft Shell Jacket - Men's  
🔟 Woolrich Arctic Parka DF  
*/

Next Steps:
- Perform deeper analysis on customer demographics to understand buying behavior.
- Explore sales trends over time (seasonality, daily, weekly trends).
- Investigate regional sales performance to identify high-revenue locations.
*/


